spring:
  application:
    name: webpos-delivery-server
  cloud:
    stream:
      function:
        bindings:
          orderConsumer-in-0: order-out-0

server:
  port: 8084

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
