spring:
  application:
    name: webpos-product-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: 123456
  r2dbc:
    url: r2dbc:mysql://localhost:3306/data
    username: root
    password: 123456
    pool:
      initial-size: 10
      max-size: 20

server:
  port: 8082

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
